from enum import Enum


class MercuryCategory(str, Enum):
    ADVERTISING = "Advertising"
    AIRLINES = "Airlines"
    ALCOHOLANDBARS = "AlcoholAndBars"
    BOOKSANDNEWSPAPER = "BooksAndNewspaper"
    CARRENTAL = "CarRental"
    CHARITY = "Charity"
    CLOTHING = "Clothing"
    CONFERENCES = "Conferences"
    EDUCATION = "Education"
    ELECTRONICS = "Electronics"
    ENTERTAINMENT = "Entertainment"
    FACILITIESEXPENSES = "FacilitiesExpenses"
    FEES = "Fees"
    FOODDELIVERY = "FoodDelivery"
    FUELANDGAS = "FuelAndGas"
    GAMBLING = "Gambling"
    GOVERNMENTSERVICES = "GovernmentServices"
    GROCERY = "Grocery"
    GROUNDTRANSPORTATION = "GroundTransportation"
    INSURANCE = "Insurance"
    INTERNETANDTELEPHONE = "InternetAndTelephone"
    LEGAL = "Legal"
    LODGING = "Lodging"
    MEDICAL = "Medical"
    MEMBERSHIPS = "Memberships"
    OFFICESUPPLIES = "OfficeSupplies"
    OTHER = "Other"
    OTHERTRAVEL = "OtherTravel"
    PARKING = "Parking"
    POLITICAL = "Political"
    PROFESSIONALSERVICES = "ProfessionalServices"
    RESTAURANTS = "Restaurants"
    RETAIL = "Retail"
    RIDESHAREANDTAXIS = "RideshareAndTaxis"
    SHIPPING = "Shipping"
    SOFTWARE = "Software"
    TAXES = "Taxes"
    UTILITIES = "Utilities"
    VEHICLEEXPENSES = "VehicleExpenses"

    def __str__(self) -> str:
        return str(self.value)
